#### Problem
 Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.

In [1]:
import numpy
a = numpy.array([1,2,3,4], float) 
b = numpy.array([5,6,7,8], float)
print(a + b)

[ 6.  8. 10. 12.]


In [2]:
print(numpy.add(a,b))

[ 6.  8. 10. 12.]


In [3]:
print(a - b)

[-4. -4. -4. -4.]


In [5]:
print(numpy.subtract(a,b))

[-4. -4. -4. -4.]


In [6]:
print(numpy.multiply(a, b))

[ 5. 12. 21. 32.]


In [7]:
print(a/b)

[0.2        0.33333333 0.42857143 0.5       ]


In [8]:
print(numpy.divide(a,b))

[0.2        0.33333333 0.42857143 0.5       ]


In [9]:
print(a % b)

[1. 2. 3. 4.]


In [10]:
print(numpy.mod(a,b))

[1. 2. 3. 4.]


In [11]:
print(a**b)

[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [12]:
print(numpy.power(a,b))

[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


#### Task :
You are given two integer arrays, A and B of dimensions NXM.

Your task is to perform the following operations:

Add ( A + B)

Subtract ( A – B)

Multiply ( A * B)

Integer Division (A / B)

Mod (A % B)

Power (A ** B)


#### Input Format :
The first line contains two space separated integers, N and M.

The next N lines contains M space separated integers of array A.

The following N lines contains M space separated integers of array B. 

#### Output Format :
Print the result of each operation in the given order under Task.

In [3]:
import numpy
N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.zeros(N, int))

1 4
[[0 0 0 0]]
[[0 0 0 0]]
