#### Problem
Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined: 

In [1]:
import numpy
array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])
print(numpy.concatenate((array_1, array_2, array_3)))

[1 2 3 4 5 6 7 8 9]


if an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default, it is along the first dimension.

In [2]:
import numpy
array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])
print(numpy.concatenate((array_1, array_2), axis = 1))

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


#### Task :
You are given two integer arrays of size NXP and MXP ( N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.


#### Input Format :
The first line contains space separated integers N, M and P.

The next N lines contains the space separated elements of the P columns.After that, the next M lines contains the space separated elements of the P columns. 

#### Output Format :
Print the concatenated array of size (N+M)XP.

In [4]:
import numpy
P, N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(P)], int)
B = numpy.array([input().split() for _ in range(N)], int)
print(numpy.concatenate((A, B), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
