#### Problem
#### Poly
The poly tool returns the coefficients of a polynomial with the given sequence of roots.

In [2]:
import numpy
print(numpy.poly([-1, 1, 1, 10 ]))

[  1. -11.   9.  11. -10.]


#### roots
The roots tool returns the roots of a polynomial with the given coefficients.

In [3]:
print(numpy.roots([1, 0, -1]))

[-1.  1.]


#### Polyint
The polyint tool returns an antiderivative (indefinite integral) of a polynomial.

In [4]:
print(numpy.polyint([1, 1, 1]))

[0.33333333 0.5        1.         0.        ]


#### Polyder
The polyder tool returns the derivative of the specified order of a polynomial.

In [5]:
print(numpy.polyder([1,1,1,1]))

[3 2 1]


#### Polyval
The polyval tool evaluates the polynomial at specific value.

In [6]:
print(numpy.polyval([1, -2, 0, 2], 4))

34


#### Polyfit
The polyfit tool fits a polynomial of a specified order to a set of data using a least-squares approach.

In [7]:
print(numpy.polyfit([0, 1, -1, 2, -2], [0, 1, 1, 4, 4], 2))

[ 1.00000000e+00 -1.55912326e-32  1.62163648e-16]


The functions polyadd, polysub, polymul, and polydiv also handle proper addition, subtraction, multiplication, and division of polynomial coefficients, respectively. 

#### Task :
You are given the coefficients of a polynomial P.

Your task is to find the value of P at point x.

#### Input Format :
The first line contains the space separated value of the coefficients in P.

The second line contains the value of x.

#### Output Format :
Print the desired value.

In [8]:
import numpy
poly = [float(x) for x in input().split()]
x = float(input())
print(numpy.polyval(poly, x))

1.1 2 3
0
3.0
