#### Problem
#### Shape :
The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.
##### (a). Using shape to get array dimensions

In [3]:
import numpy
my_1D_array = numpy.array([1,2,3,4,5])
print((my_1D_array).shape)

(5,)


In [4]:
my_2D_array = numpy.array([[1,2],[3,4],[6,5]])
print((my_2D_array).shape)

(3, 2)


#### (b). Using shape to change array dimensions

In [5]:
import numpy
change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3,2)
print(change_array)

[[1 2]
 [3 4]
 [5 6]]


#### Reshape
The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

#### Task :
You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

#### Input Format :
A single line of input containing 9 space separated integers.

#### Output Format :
Print the 3X3 NumPy array.

In [12]:
import numpy
print(numpy.array(input().split(), int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
