#### Problem
#### zeros
The zeros tool returns a new array with a given shape and type filled with 0’s.

In [3]:
import numpy
print(numpy.zeros((1,2))) #Default type is flaot

[[0. 0.]]


In [4]:
print(numpy.zeros((1,2), dtype=numpy.int)) #Type changes to int

[[0 0]]


<ipython-input-4-f3bf21a5c31b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.zeros((1,2), dtype=numpy.int)) #Type changes to int


#### ones
The ones tool returns a new array with a given shape and type filled with 1’s.

In [5]:
import numpy
print(numpy.ones((1,2))) #Default type is flaot

[[1. 1.]]


In [6]:
print(numpy.ones((1,2), dtype = numpy.int)) #Type changes to int

[[1 1]]


<ipython-input-6-1a92cf1d228b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.ones((1,2), dtype = numpy.int)) #Type changes to int


#### Task :
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones. 

#### Input Format :
A single line containing the space-separated integers. 

#### Output Format :
First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool. 

#### Explanation :
Print the array built using numpy.zeros and numpy.ones tools and you get the result as shown.  

In [7]:
import numpy
N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.ones(N, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
